package dev.tlong.biodex.data.place

import android.content.Context
import android.util.Log
import dev.tlong.biodex.domain.GazetteerPlace
import dev.tlong.biodex.domain.parseGazetteerLine
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext

/**
 * D68. The region's place names, bundled as an asset so the "Where was this?" prompt can
 * suggest and validate with no network — the same bargain the catalogue makes (3.2). Roughly
 * 45,000 towns, parks, trails, beaches and landmarks across California, Oregon and Washington,
 * generated by `tools/places/build_places.py` from the GeoNames dump.
 */
fun interface PlaceGazetteer {

    /**
     * Every place in the region, in no order the caller should rely on — the ranking is
     * [dev.tlong.biodex.domain.suggestPlaces]' job. Suspending because the first call reads a
     * 900 KB asset; every call after it is the cached list.
     */
    suspend fun places(): List<GazetteerPlace>

    companion object {
        /** No place list at all — the JVM suite's default, and the app's if the asset is gone. */
        val None = PlaceGazetteer { emptyList() }
    }
}

/**
 * The asset, parsed once and held for the process. The file is tab-separated rather than JSON
 * because it is 45,000 rows of three fields: `kotlinx.serialization` over that shape costs
 * both the parse time and the object churn for nothing a `split` does not give.
 */
class AssetPlaceGazetteer(
    private val context: Context,
    private val assetPath: String = ASSET_PATH,
) : PlaceGazetteer {

    private val lock = Mutex()
    private var cached: List<GazetteerPlace>? = null

    override suspend fun places(): List<GazetteerPlace> {
        cached?.let { return it }
        return lock.withLock {
            cached ?: withContext(Dispatchers.IO) { read() }.also { cached = it }
        }
    }

    private fun read(): List<GazetteerPlace> = try {
        context.assets.open(assetPath).bufferedReader().useLines { lines ->
            lines.mapNotNull(::parseGazetteerLine).toList()
        }
    } catch (e: Exception) {
        // A missing or truncated asset costs the suggestions, not the registration: the
        // prompt falls back to the places this collection already uses.
        Log.w(TAG, "No place list at $assetPath: ${e.message}")
        emptyList()
    }

    private companion object {
        const val ASSET_PATH = "places/pacific.tsv"
        const val TAG = "PlaceGazetteer"
    }
}
