package dev.tlong.biodex.data.catalogue

import android.util.Log
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonObject

/**
 * Dr. Duke's Phytochemical and Ethnobotanical Databases (USDA ARS, **CC0**), bundled as one
 * asset and read entirely in process — ARCHITECTURE.md 11.2, M18 and D3. A user-added plant's
 * medicinal tag comes from here, so it works in airplane mode and costs no request.
 *
 * Three things this class is careful about.
 *
 * **It may have nothing to read.** The asset is generated by the catalogue pipeline and may not
 * be in the APK yet; a missing or malformed asset is logged and becomes an empty index, exactly
 * as `CatalogueImporter` treats a missing catalogue. "No Duke's record" is an ordinary state on
 * the card (11.3 step 2), so an empty index degrades to that rather than to an error.
 *
 * **It parses lazily.** Only a plant confirmation card ever asks, so a session that never adds
 * a plant never pays for parsing 13,010 taxa.
 *
 * **Synonyms genuinely bite (R15).** Duke's keys on the genus and species strings of its own
 * era. Oregon grape has four records as *Mahonia aquifolium* and none as *Berberis aquifolium*,
 * so [lookup] tries the GBIF-accepted binomial and then each GBIF synonym in turn.
 */
class DukeIndex(
    private val assets: AssetReader,
    private val assetPath: String = DUKE_ASSET_PATH,
) {

    private val taxa: Map<String, DukeRecord> by lazy { load() }

    /** True once the asset has been read and had something in it; for the card's honest label. */
    val available: Boolean get() = taxa.isNotEmpty()

    /**
     * Tries [accepted] first, then [synonyms] in order, and returns the first hit — the same
     * order the build-time pipeline joins in, so a species tagged medicinal in the catalogue
     * and the same species added by hand agree.
     */
    fun lookup(accepted: String?, synonyms: List<String> = emptyList()): DukeRecord? {
        if (taxa.isEmpty()) return null
        for (name in listOfNotNull(accepted) + synonyms) {
            taxa[dukeKey(name)]?.let { return it }
        }
        return null
    }

    private fun load(): Map<String, DukeRecord> {
        val text = try {
            assets.open(assetPath)?.use { it.readBytes().decodeToString() }
        } catch (e: Exception) {
            Log.e(TAG, "Duke's asset '$assetPath' could not be read.", e)
            return emptyMap()
        }
        if (text == null) {
            Log.w(TAG, "Duke's asset '$assetPath' is not bundled; user-added plants get no tag.")
            return emptyMap()
        }
        return try {
            parseDukeIndex(text)
        } catch (e: Exception) {
            Log.e(TAG, "Duke's asset '$assetPath' could not be parsed.", e)
            emptyMap()
        }
    }

    companion object {
        /**
         * The one rule the pipeline's Python and this Kotlin both implement (11.2), written
         * down in both so they cannot drift: three distinct non-`Poison` activities is what
         * "medicinal" means. `Poison` is never one of them — it drives the caution, not the tag
         * (D14).
         */
        fun medicinalByRule(record: DukeRecord?): Boolean =
            record != null && record.activities.size >= MEDICINAL_ACTIVITY_THRESHOLD

        const val MEDICINAL_ACTIVITY_THRESHOLD = 3

        private const val TAG = "DukeIndex"
    }
}

const val DUKE_ASSET_PATH = "catalogue/duke_ethnobot.json"

/** The Duke's credit line (11.1). CC0 is what makes bundling the file legitimate. */
const val DUKE_ATTRIBUTION =
    "Dr. Duke's Phytochemical and Ethnobotanical Databases · USDA ARS · CC0"

/**
 * One species' ethnobotanical record. [activities] excludes `Poison`, which is carried
 * separately as [poison] because it is a checklist rather than a tag — a "toxic" badge on some
 * species would imply the rest are safe, which is the wrong inference for a foraging app (D14).
 */
data class DukeRecord(
    val activities: List<String>,
    val recordCount: Int,
    val poison: Boolean,
)

/**
 * Duke's rows are keyed on `GENUS` + `SPECIES`, so every name is reduced to its first two
 * tokens, lower-cased, with whitespace collapsed (R15). A GBIF synonym that is a trinomial
 * (*Sambucus caerulea velutina*) therefore joins on its binomial, which is what Duke's holds.
 */
internal fun dukeKey(name: String): String =
    name.trim().lowercase().split(WHITESPACE).filter { it.isNotEmpty() }.take(2).joinToString(" ")

private val WHITESPACE = Regex("\\s+")

private val json = Json { ignoreUnknownKeys = true }

/**
 * The asset is `{"activities": [...], "taxa": {"genus species": {"a": [3, 17], "n": 105,
 * "p": true}}}` — 11.3's "activities deduplicated into a string table", which is what keeps
 * 82,873 records inside 2 MB. The flat shape `{"genus species": {"a": ["Astringent"], …}}`
 * that the same paragraph also shows is accepted too, so whichever the pipeline emits parses.
 */
internal fun parseDukeIndex(text: String): Map<String, DukeRecord> {
    val root = json.parseToJsonElement(text).jsonObject
    val table = (root["activities"] as? JsonArray)
        ?.mapNotNull { (it as? JsonPrimitive)?.content }
    val taxa = (root["taxa"] as? JsonObject) ?: root
    val out = HashMap<String, DukeRecord>(taxa.size)
    for ((name, element) in taxa) {
        val row = element as? JsonObject ?: continue
        val activities = (row["a"] as? JsonArray).orEmpty().mapNotNull { entry ->
            val primitive = entry as? JsonPrimitive ?: return@mapNotNull null
            // A string is the activity name; a number is an index into the string table.
            if (primitive.isString) primitive.content
            else table?.getOrNull(primitive.content.toIntOrNull() ?: -1)
        }
        out[dukeKey(name)] = DukeRecord(
            activities = activities.distinct(),
            recordCount = (row["n"] as? JsonPrimitive)?.content?.toIntOrNull() ?: 0,
            poison = (row["p"] as? JsonPrimitive)?.content?.toBooleanStrictOrNull() ?: false,
        )
    }
    return out
}
