package dev.tlong.biodex.domain

import java.text.Normalizer

/**
 * D68. The offline place list and the search over it — everything the "Where was this?" prompt
 * does except read the asset, so the JVM suite can pin the ranking with no device.
 *
 * Two sources feed the prompt. The **bundled gazetteer** is 45,000 towns, parks, trails and
 * landmarks across the region, generated by `tools/places/build_places.py`. The **places this
 * collection already uses** are the labels on existing sightings, and they come first for a
 * matching query: a life list returns to the same handful of places, and one of them is a trail
 * or a back garden no gazetteer holds.
 */

/** One row of the asset. [tier] is 0 for a town, 1 for a park or trail, 2 for a landmark. */
data class GazetteerPlace(
    val name: String,
    val state: String,
    val tier: Int,
) {
    /** What a sighting stores — the same "Locality, Region" shape the geocoder produces (D56). */
    val label: String get() = "$name, ${stateName(state)}"

    /** Folded once at parse, because the search folds the query and then scans all 45,000. */
    val folded: String = foldPlace(name)

    /** The same for the whole label, which is what the validation compares against. */
    val foldedLabel: String = foldPlace(label)
}

/** The three states the shipped list covers, spelled the way the geocoder spells them. */
private fun stateName(code: String): String = when (code) {
    "CA" -> "California"
    "OR" -> "Oregon"
    "WA" -> "Washington"
    else -> code
}

/**
 * `name<TAB>state<TAB>tier`, or null for a line the asset should not have carried. A bad line
 * is skipped rather than thrown: a place list that lost its last byte in a bad install should
 * cost the suggestions it holds, not the app's ability to register a catch.
 */
fun parseGazetteerLine(line: String): GazetteerPlace? {
    val fields = line.split('\t')
    if (fields.size != 3) return null
    val name = fields[0].trim()
    val state = fields[1].trim()
    val tier = fields[2].trim().toIntOrNull()
    if (name.isEmpty() || state.isEmpty() || tier == null) return null
    return GazetteerPlace(name = name, state = state, tier = tier)
}

/**
 * Lower-cased, accents stripped, and every run of punctuation or whitespace flattened to one
 * space. Unlike [SearchMatch.fold], which removes separators entirely, this keeps the word
 * boundaries — they are what lets "reyes" rank *Point Reyes Station* above *Reyesville*,
 * and a place name is several words far more often than a species name is.
 */
fun foldPlace(text: String): String {
    val decomposed = Normalizer.normalize(text, Normalizer.Form.NFD)
    val out = StringBuilder(decomposed.length)
    var pendingSpace = false
    for (ch in decomposed) {
        when {
            ch.isLetterOrDigit() -> {
                if (pendingSpace && out.isNotEmpty()) out.append(' ')
                pendingSpace = false
                out.append(ch.lowercaseChar())
            }
            // An apostrophe joins rather than separates: nobody types "o brien".
            ch == '\'' || ch == '\u2019' -> Unit
            // The accent NFD just split off its letter — dropping it is the fold's point.
            ch.category == CharCategory.NON_SPACING_MARK -> Unit
            else -> pendingSpace = true
        }
    }
    return out.toString()
}

/** Where the query landed in a name: at the front, at a word, or just somewhere inside it. */
private fun matchRank(folded: String, query: String): Int = when {
    folded.startsWith(query) -> 0
    folded.contains(" $query") -> 1
    folded.contains(query) -> 2
    else -> NO_MATCH
}

private const val NO_MATCH = 9

/**
 * The labels to offer for what the user has typed so far, best first and at most [limit].
 *
 * An empty query offers [recent] alone — opening the prompt with nowhere to go is worse than
 * opening it on the places this collection already knows, and 45,000 names in alphabetical
 * order would be a list of numbers. Otherwise both sources are ranked together by how well the
 * name matches, then by whether it is already in the collection, then by tier, so a town beats
 * a hill of the same name and a short name beats a long one that merely contains it.
 */
fun suggestPlaces(
    query: String,
    places: List<GazetteerPlace>,
    recent: List<String>,
    limit: Int = 8,
): List<String> {
    val folded = foldPlace(query)
    if (folded.isEmpty()) return recent.take(limit)

    data class Hit(val label: String, val match: Int, val known: Int, val tier: Int)

    val hits = ArrayList<Hit>()
    for (label in recent) {
        val rank = matchRank(foldPlace(label), folded)
        if (rank != NO_MATCH) hits += Hit(label, rank, known = 0, tier = 0)
    }
    val alreadyOffered = recent.toHashSet()
    for (place in places) {
        val rank = matchRank(place.folded, folded)
        if (rank == NO_MATCH) continue
        val label = place.label
        if (label in alreadyOffered) continue
        hits += Hit(label, rank, known = 1, tier = place.tier)
    }

    return hits
        .sortedWith(
            compareBy<Hit> { it.match }
                .thenBy { it.known }
                .thenBy { it.tier }
                .thenBy { it.label.length }
                .thenBy { it.label },
        )
        .map { it.label }
        .take(limit)
}

/**
 * The label [text] names, or null if neither source holds it — the validation D68 asks for.
 *
 * It returns the *place's own* spelling rather than a yes, and that is the point: the match
 * folds case, accents and spacing on both sides, so "bear valley,  california" is a hit, and
 * writing that string onto a sighting would ship the typo the check just caught. What lands on
 * the capture is always the list's own label.
 */
fun canonicalPlace(text: String, places: List<GazetteerPlace>, recent: List<String>): String? {
    val folded = foldPlace(text)
    if (folded.isEmpty()) return null
    recent.firstOrNull { foldPlace(it) == folded }?.let { return it }
    return places.firstOrNull { it.foldedLabel == folded }?.label
}
