package dev.tlong.biodex.domain

import java.text.Normalizer

/**
 * D68. The offline place list and the search over it — everything the "Where was this?" prompt
 * does except read the asset, so the JVM suite can pin the ranking with no device.
 *
 * Two sources feed the prompt. The **bundled gazetteer** is 45,000 towns, parks, trails and
 * landmarks across the region, generated by `tools/places/build_places.py`. The **places this
 * collection already uses** are the labels on existing sightings, and they come first for a
 * matching query: a life list returns to the same handful of places, and one of them is a trail
 * or a back garden no gazetteer holds.
 */

/**
 * One row of the asset. [tier] is 0 for a town, 1 for a park or trail, 2 for a landmark;
 * [lat]/[lng] are GeoNames' point for it, to four decimals.
 */
data class GazetteerPlace(
    val name: String,
    val state: String,
    val tier: Int,
    val lat: Double,
    val lng: Double,
) {
    /**
     * What a sighting stores — the same "Locality, Region" shape the geocoder produces (D56).
     * Built once: the search compares and offers labels, and allocating 45,000 of them per
     * keystroke was most of what made a one-letter query take 400 ms on the phone.
     */
    val label: String = "$name, ${stateName(state)}"

    /** Folded once at parse, because the search folds the query and then scans all 45,000. */
    val folded: String = foldPlace(name)

    /** The same for the whole label, which is what the validation compares against. */
    val foldedLabel: String = foldPlace(label)
}

/** The three states the shipped list covers, spelled the way the geocoder spells them. */
private fun stateName(code: String): String = when (code) {
    "CA" -> "California"
    "OR" -> "Oregon"
    "WA" -> "Washington"
    else -> code
}

private val TRAILING_STATE_CODE = Regex(""",\s*(CA|OR|WA)\s*$""", RegexOption.IGNORE_CASE)

/**
 * "La Jolla, CA" spelled the way the list spells it — "La Jolla, California" — so a label typed
 * with the postal code, as most of the owner's older sightings were, still finds its place and
 * its point. Anything else comes back unchanged.
 */
internal fun expandStateCode(text: String): String =
    TRAILING_STATE_CODE.replace(text) { ", " + stateName(it.groupValues[1].uppercase()) }

/**
 * `name<TAB>state<TAB>tier<TAB>lat<TAB>lng`, or null for a line the asset should not have
 * carried. A bad line is skipped rather than thrown: a place list that lost its last byte in a
 * bad install should cost the suggestions it holds, not the app's ability to register a catch.
 */
fun parseGazetteerLine(line: String): GazetteerPlace? {
    val fields = line.split('\t')
    if (fields.size != 5) return null
    val name = fields[0].trim()
    val state = fields[1].trim()
    val tier = fields[2].trim().toIntOrNull()
    val lat = fields[3].trim().toDoubleOrNull()
    val lng = fields[4].trim().toDoubleOrNull()
    if (name.isEmpty() || state.isEmpty() || tier == null || lat == null || lng == null) {
        return null
    }
    return GazetteerPlace(name = name, state = state, tier = tier, lat = lat, lng = lng)
}

/**
 * What the place prompt hands a registration: the words that go on the sighting and, when the
 * list knows the place, where it is. The coordinates are a *fallback* for the photo's own —
 * the registrar writes them only when the EXIF had none (D68), because a photograph's GPS is
 * where the animal was and a town's point is only near it.
 */
data class PlaceAnswer(
    val label: String,
    val lat: Double? = null,
    val lng: Double? = null,
)

/**
 * Lower-cased, accents stripped, and every run of punctuation or whitespace flattened to one
 * space. Unlike [SearchMatch.fold], which removes separators entirely, this keeps the word
 * boundaries — they are what lets "reyes" rank *Point Reyes Station* above *Reyesville*,
 * and a place name is several words far more often than a species name is.
 */
fun foldPlace(text: String): String {
    val decomposed = Normalizer.normalize(text, Normalizer.Form.NFD)
    val out = StringBuilder(decomposed.length)
    var pendingSpace = false
    for (ch in decomposed) {
        when {
            ch.isLetterOrDigit() -> {
                if (pendingSpace && out.isNotEmpty()) out.append(' ')
                pendingSpace = false
                out.append(ch.lowercaseChar())
            }
            // An apostrophe joins rather than separates: nobody types "o brien".
            ch == '\'' || ch == '\u2019' -> Unit
            // The accent NFD just split off its letter — dropping it is the fold's point.
            ch.category == CharCategory.NON_SPACING_MARK -> Unit
            else -> pendingSpace = true
        }
    }
    return out.toString()
}

/**
 * Where the query landed in a name: at the front, at a word, or just somewhere inside it.
 * [atWord] is the query with a leading space, built once by the caller rather than once per
 * place.
 */
private fun matchRank(folded: String, query: String, atWord: String): Int = when {
    folded.startsWith(query) -> 0
    folded.contains(atWord) -> 1
    folded.contains(query) -> 2
    else -> NO_MATCH
}

private const val NO_MATCH = 9

/**
 * The labels to offer for what the user has typed so far, best first and at most [limit].
 *
 * An empty query offers [recent] alone — opening the prompt with nowhere to go is worse than
 * opening it on the places this collection already knows, and 45,000 names in alphabetical
 * order would be a list of numbers. Otherwise both sources are ranked together by how well the
 * name matches, then by whether it is already in the collection, then by tier, so a town beats
 * a hill of the same name and a short name beats a long one that merely contains it.
 */
fun suggestPlaces(
    query: String,
    places: List<GazetteerPlace>,
    recent: List<String>,
    limit: Int = 8,
): List<String> {
    val folded = foldPlace(query)
    if (folded.isEmpty()) return recent.take(limit)
    val atWord = " $folded"

    // Every hit falls in one of a handful of buckets — (match, known, tier) — and the buckets
    // are already in rank order. So rather than sort every hit (a one-letter query hits most of
    // the 45,000), fill the buckets and sort only the few it takes to reach [limit].
    val buckets = Array(MATCH_RANKS * 2 * TIERS) { ArrayList<String>() }
    fun bucket(match: Int, known: Int, tier: Int) =
        buckets[(match * 2 + known) * TIERS + tier.coerceIn(0, TIERS - 1)]

    val alreadyOffered = HashSet<String>()
    for (label in recent) {
        val rank = matchRank(foldPlace(label), folded, atWord)
        if (rank != NO_MATCH && alreadyOffered.add(label)) bucket(rank, known = 0, tier = 0) += label
    }
    for (place in places) {
        val rank = matchRank(place.folded, folded, atWord)
        if (rank == NO_MATCH || place.label in alreadyOffered) continue
        bucket(rank, known = 1, tier = place.tier) += place.label
    }

    val out = ArrayList<String>(limit)
    for (hits in buckets) {
        if (out.size >= limit) break
        if (hits.isEmpty()) continue
        hits.sortWith(compareBy<String> { it.length }.thenBy { it })
        for (label in hits) {
            if (out.size >= limit) break
            out += label
        }
    }
    return out
}

private const val MATCH_RANKS = 3
private const val TIERS = 3

/**
 * The place [text] names, or null if neither source holds it.
 *
 * It returns the *place's own* spelling rather than a yes, and that is the point: the match
 * folds case, accents and spacing on both sides, so "bear valley,  california" is a hit, and
 * writing that string onto a sighting would store the sloppiness the match forgave. A label
 * this collection already uses keeps its own spelling; the coordinates come from the bundled
 * list whenever it holds the same place, so a recent place that started life as a suggestion,
 * a reverse-geocoded name or a typed "Town, CA" still maps.
 */
fun canonicalPlace(text: String, places: List<GazetteerPlace>, recent: List<String>): PlaceAnswer? {
    val folded = foldPlace(expandStateCode(text))
    if (folded.isEmpty()) return null
    val listed = places.firstOrNull { it.foldedLabel == folded }
    val used = recent.firstOrNull { foldPlace(expandStateCode(it)) == folded }
    val label = used ?: listed?.label ?: return null
    return PlaceAnswer(label = label, lat = listed?.lat, lng = listed?.lng)
}
